[package]
name = "wayne-manager"
version = "0.1.0"
authors = ["Kabir Kwatra <kabir@kwatra.me>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"

[dependencies.serenity]
version = "0.8.5"
default-features = false
features = ["client", "model", "http", "rustls_backend", "cache"]
